/*
 ==============================================================================
 
 This file was auto-generated by the Introjucer!
 
 It contains the basic framework code for a JUCE plugin editor.
 
 ==============================================================================
 */

//#include "OOBaseAudioProcessor.h"
#include "OOBaseProcessorEditor.h"


//==============================================================================
OOBaseProcessorEditor::OOBaseProcessorEditor (OOBaseAudioProcessor& p)
: AudioProcessorEditor (&p), processor (p),repainter(this)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (400, 300);
    
    p.addListener(this);
    
}

OOBaseProcessorEditor::~OOBaseProcessorEditor()
{
}

//==============================================================================
void OOBaseProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);
    
    g.setColour (Colours::black);
    g.setFont (15.0f);
//    g.drawFittedText (String(processor.testOsc), getLocalBounds(), Justification::centred, 1);
}

void OOBaseProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
}

// for now repaint should be handled in individual components
void OOBaseProcessorEditor::audioProcessorParameterChanged (AudioProcessor* processor,
                                                            int parameterIndex,
                                                            float newValue){
//    repainter.triggerAsyncUpdate();
}

void OOBaseProcessorEditor::audioProcessorChanged (AudioProcessor* processor) {
//    repainter.triggerAsyncUpdate();
}

